const gameService = require('./game');
const uuidv4 = require('uuid/v4');

const { UnitData, StructureData } = require('shared');

const campaigns = {
    startingProvinces: [
        'haven',
        'free-city'
    ],
    provinces: [
        // Fallen Haven
        ['cartasone', 'eagle-nest', 'haven', 'milos', 'high-point', 'ayden', 'snake-river', 'canuck', 'point-harbour', 'rock-castle', 'sparta', 'aberdeen', 'delos', 'elkin', 'norwood', 'kinabal', 'marshall', 'roanoke', 'creedmoor', 'garland', 'chaos'],
        // The last hope campaign
        ['free-city', 'lachine', 'sutton', 'rolland', 'chertsy', 'bromont', 'rawdon', 'granby', 'alma', 'brome-lake', 'hull', 'norenda', 'brimstone', 'thetfordmines', 'sherbrooke', 'masson-lake', 'kamouraska', 'esterel', 'valleyfield', 'orford', 'three-rivers']
    ]
};

const missions = {
    "eagle-nest": {
        "description": "Rebels need help",
        "objective": "Destroy Rocket Launcher",
        "reward": "Rebel forces will join you",
    },
    "milos": {
        "description": "Annihilate their research capacity",
        "objective": "Destroy the Laboratory",
        "reward": "5000 R. Pts",
    },
    'canuck': {
        "description": "Special units under attack by the enemy",
        "objective": "Destroy all enemy units",
        "reward": "Special units",
    },
    "kinabal": {
        "description": "",
        "objective": "Destroy all the enemy units without destroying a single building",
        "reward": "5000 Cr.",
    }
};

const walls = {
    "haven": [
        { "x": 31, "y": 16 },
        { "x": 31, "y": 17 },
        { "x": 31, "y": 18 },
        { "x": 29, "y": 19 },
        { "x": 30, "y": 19 },
        { "x": 31, "y": 19 }
    ],
    "eagle-nest": [
        { "x": 00, "y": 24 },
        { "x": 25, "y": 00 },
        { "x": 24, "y": 01 },
        { "x": 25, "y": 01 },
        { "x": 24, "y": 02 },
        { "x": 25, "y": 02 },
        { "x": 24, "y": 03 },
        { "x": 25, "y": 03 },
        { "x": 26, "y": 03 },
        { "x": 25, "y": 05 },
        { "x": 25, "y": 06 },
        { "x": 26, "y": 06 },
        { "x": 25, "y": 07 },
        { "x": 26, "y": 07 },
        { "x": 27, "y": 07 },
        { "x": 28, "y": 07 },
        { "x": 29, "y": 07 },
        { "x": 30, "y": 07 },
        { "x": 25, "y": 08 },
        { "x": 26, "y": 08 },
        { "x": 27, "y": 08 },
        { "x": 28, "y": 08 },
        { "x": 29, "y": 08 },
        { "x": 30, "y": 08 },
        { "x": 31, "y": 08 },
        { "x": 30, "y": 09 },
        { "x": 31, "y": 09 },
        { "x": 26, "y": 10 },
        { "x": 27, "y": 10 },
        { "x": 28, "y": 10 },
        { "x": 30, "y": 10 },
        { "x": 31, "y": 10 },
        { "x": 28, "y": 11 },
        { "x": 30, "y": 11 },
        { "x": 31, "y": 11 },
        { "x": 28, "y": 12 },
        { "x": 30, "y": 12 },
        { "x": 31, "y": 12 },
        { "x": 23, "y": 13 },
        { "x": 28, "y": 13 },
        { "x": 30, "y": 13 },
        { "x": 31, "y": 13 },
        { "x": 32, "y": 13 },
        { "x": 33, "y": 13 },
        { "x": 34, "y": 13 },
        { "x": 35, "y": 13 },
        { "x": 41, "y": 13 },
        { "x": 42, "y": 13 },
        { "x": 26, "y": 14 },
        { "x": 27, "y": 14 },
        { "x": 28, "y": 14 },
        { "x": 30, "y": 14 },
        { "x": 31, "y": 14 },
        { "x": 32, "y": 14 },
        { "x": 33, "y": 14 },
        { "x": 34, "y": 14 },
        { "x": 35, "y": 14 },
        { "x": 37, "y": 14 },
        { "x": 38, "y": 14 },
        { "x": 39, "y": 14 },
        { "x": 41, "y": 14 },
        { "x": 42, "y": 14 },
        { "x": 22, "y": 15 },
        { "x": 30, "y": 15 },
        { "x": 31, "y": 15 },
        { "x": 32, "y": 15 },
        { "x": 41, "y": 15 },
        { "x": 42, "y": 15 },
        { "x": 17, "y": 16 },
        { "x": 20, "y": 16 },
        { "x": 24, "y": 16 },
        { "x": 34, "y": 16 },
        { "x": 35, "y": 16 },
        { "x": 36, "y": 16 },
        { "x": 37, "y": 16 },
        { "x": 38, "y": 16 },
        { "x": 39, "y": 16 },
        { "x": 40, "y": 16 },
        { "x": 41, "y": 16 },
        { "x": 42, "y": 16 },
        { "x": 25, "y": 17 },
        { "x": 26, "y": 17 },
        { "x": 27, "y": 17 },
        { "x": 28, "y": 17 },
        { "x": 34, "y": 17 },
        { "x": 35, "y": 17 },
        { "x": 36, "y": 17 },
        { "x": 37, "y": 17 },
        { "x": 38, "y": 17 },
        { "x": 39, "y": 17 },
        { "x": 40, "y": 17 },
        { "x": 41, "y": 17 },
        { "x": 42, "y": 17 },
        { "x": 21, "y": 18 },
        { "x": 23, "y": 18 },
        { "x": 24, "y": 18 },
        { "x": 25, "y": 18 },
        { "x": 17, "y": 19 },
        { "x": 20, "y": 19 },
        { "x": 22, "y": 19 },
        { "x": 23, "y": 19 },
        { "x": 29, "y": 19 },
        { "x": 22, "y": 20 },
        { "x": 06, "y": 21 },
        { "x": 13, "y": 21 },
        { "x": 22, "y": 21 },
        { "x": 25, "y": 21 },
        { "x": 28, "y": 21 },
        { "x": 30, "y": 21 },
        { "x": 31, "y": 21 },
        { "x": 05, "y": 22 },
        { "x": 18, "y": 22 },
        { "x": 19, "y": 22 },
        { "x": 20, "y": 22 },
        { "x": 21, "y": 22 },
        { "x": 22, "y": 22 },
        { "x": 30, "y": 22 },
        { "x": 08, "y": 23 },
        { "x": 10, "y": 23 },
        { "x": 12, "y": 23 },
        { "x": 14, "y": 23 },
        { "x": 16, "y": 23 },
        { "x": 18, "y": 23 },
        { "x": 26, "y": 23 },
        { "x": 28, "y": 23 },
        { "x": 30, "y": 23 },
        { "x": 18, "y": 24 },
        { "x": 22, "y": 24 },
        { "x": 23, "y": 24 },
        { "x": 24, "y": 24 },
        { "x": 30, "y": 24 },
        { "x": 05, "y": 25 },
        { "x": 08, "y": 25 },
        { "x": 13, "y": 25 },
        { "x": 14, "y": 25 },
        { "x": 15, "y": 25 },
        { "x": 16, "y": 25 },
        { "x": 17, "y": 25 },
        { "x": 18, "y": 25 },
        { "x": 20, "y": 25 },
        { "x": 24, "y": 25 },
        { "x": 27, "y": 25 },
        { "x": 30, "y": 25 },
        { "x": 11, "y": 26 },
        { "x": 13, "y": 26 },
        { "x": 22, "y": 26 },
        { "x": 23, "y": 26 },
        { "x": 24, "y": 26 },
        { "x": 30, "y": 26 },
        { "x": 12, "y": 27 },
        { "x": 13, "y": 27 },
        { "x": 20, "y": 27 },
        { "x": 27, "y": 27 },
        { "x": 28, "y": 27 },
        { "x": 29, "y": 27 },
        { "x": 30, "y": 27 },
        { "x": 07, "y": 28 },
        { "x": 09, "y": 28 },
        { "x": 12, "y": 28 },
        { "x": 19, "y": 28 },
        { "x": 23, "y": 28 },
        { "x": 24, "y": 28 },
        { "x": 27, "y": 28 },
        { "x": 28, "y": 28 },
        { "x": 12, "y": 29 },
        { "x": 16, "y": 29 },
        { "x": 18, "y": 29 },
        { "x": 23, "y": 29 },
        { "x": 28, "y": 29 },
        { "x": 12, "y": 30 },
        { "x": 22, "y": 30 },
        { "x": 23, "y": 30 },
        { "x": 28, "y": 30 },
        { "x": 08, "y": 31 },
        { "x": 09, "y": 31 },
        { "x": 10, "y": 31 },
        { "x": 11, "y": 31 },
        { "x": 12, "y": 31 },
        { "x": 18, "y": 31 },
        { "x": 20, "y": 31 },
        { "x": 22, "y": 31 },
        { "x": 23, "y": 31 },
        { "x": 25, "y": 31 },
        { "x": 26, "y": 31 },
        { "x": 28, "y": 31 },
        { "x": 08, "y": 32 },
        { "x": 16, "y": 32 },
        { "x": 19, "y": 32 },
        { "x": 22, "y": 32 },
        { "x": 23, "y": 32 },
        { "x": 25, "y": 32 },
        { "x": 26, "y": 32 },
        { "x": 28, "y": 32 },
        { "x": 30, "y": 32 },
        { "x": 08, "y": 33 },
        { "x": 21, "y": 33 },
        { "x": 22, "y": 33 },
        { "x": 23, "y": 33 },
        { "x": 28, "y": 33 },
        { "x": 31, "y": 33 },
        { "x": 18, "y": 34 },
        { "x": 19, "y": 34 },
        { "x": 21, "y": 34 },
        { "x": 22, "y": 34 },
        { "x": 23, "y": 34 },
        { "x": 25, "y": 34 },
        { "x": 26, "y": 34 },
        { "x": 28, "y": 34 },
        { "x": 29, "y": 34 },
        { "x": 18, "y": 35 },
        { "x": 19, "y": 35 },
        { "x": 20, "y": 35 },
        { "x": 21, "y": 35 },
        { "x": 22, "y": 35 },
        { "x": 25, "y": 35 },
        { "x": 26, "y": 35 },
        { "x": 28, "y": 35 },
        { "x": 29, "y": 35 },
        { "x": 30, "y": 35 },
        { "x": 31, "y": 35 },
        { "x": 32, "y": 35 },
        { "x": 19, "y": 36 },
        { "x": 20, "y": 36 },
        { "x": 21, "y": 36 },
        { "x": 22, "y": 36 },
        { "x": 29, "y": 36 },
        { "x": 30, "y": 36 },
        { "x": 31, "y": 36 },
        { "x": 32, "y": 36 }
    ]
}

const roads = {
    "haven": [
        { "x": 18, "y": 18 },
        { "x": 17, "y": 19 },
        { "x": 18, "y": 19 },
        { "x": 18, "y": 20 },
        { "x": 19, "y": 20 },
        { "x": 20, "y": 20 },
        { "x": 21, "y": 20 },
        { "x": 25, "y": 20 },
        { "x": 26, "y": 20 },
        { "x": 21, "y": 21 },
        { "x": 25, "y": 21 },
        { "x": 26, "y": 21 },
        { "x": 30, "y": 21 },
        { "x": 31, "y": 21 },
        { "x": 32, "y": 21 },
        { "x": 21, "y": 22 },
        { "x": 25, "y": 22 },
        { "x": 26, "y": 22 },
        { "x": 27, "y": 22 },
        { "x": 28, "y": 22 },
        { "x": 29, "y": 22 },
        { "x": 30, "y": 22 },
        { "x": 21, "y": 23 },
        { "x": 22, "y": 23 },
        { "x": 23, "y": 23 },
        { "x": 24, "y": 23 },
        { "x": 25, "y": 23 },
        { "x": 26, "y": 23 },
        { "x": 30, "y": 23 },
        { "x": 22, "y": 24 },
        { "x": 23, "y": 24 },
        { "x": 24, "y": 24 },
        { "x": 25, "y": 24 },
        { "x": 30, "y": 24 },
        { "x": 22, "y": 25 },
        { "x": 23, "y": 25 },
        { "x": 24, "y": 25 },
        { "x": 25, "y": 25 },
        { "x": 30, "y": 25 },
        { "x": 18, "y": 26 },
        { "x": 19, "y": 26 },
        { "x": 20, "y": 26 },
        { "x": 21, "y": 26 },
        { "x": 22, "y": 26 },
        { "x": 23, "y": 26 },
        { "x": 24, "y": 26 },
        { "x": 25, "y": 26 },
        { "x": 30, "y": 26 },
        { "x": 22, "y": 27 },
        { "x": 30, "y": 27 },
        { "x": 22, "y": 28 },
        { "x": 30, "y": 28 },
        { "x": 22, "y": 29 },
        { "x": 30, "y": 29 },
        { "x": 22, "y": 30 },
        { "x": 30, "y": 30 },
        { "x": 22, "y": 31 },
        { "x": 22, "y": 32 },
        { "x": 17, "y": 18 }
    ],
    "eagle-nest": [
        { "x": 18, "y": 00 },
        { "x": 19, "y": 00 },
        { "x": 20, "y": 00 },
        { "x": 21, "y": 00 },
        { "x": 22, "y": 00 },
        { "x": 23, "y": 00 },
        { "x": 18, "y": 01 },
        { "x": 23, "y": 01 },
        { "x": 07, "y": 02 },
        { "x": 08, "y": 02 },
        { "x": 09, "y": 02 },
        { "x": 10, "y": 02 },
        { "x": 11, "y": 02 },
        { "x": 12, "y": 02 },
        { "x": 13, "y": 02 },
        { "x": 14, "y": 02 },
        { "x": 15, "y": 02 },
        { "x": 16, "y": 02 },
        { "x": 17, "y": 02 },
        { "x": 18, "y": 02 },
        { "x": 23, "y": 02 },
        { "x": 06, "y": 03 },
        { "x": 07, "y": 03 },
        { "x": 14, "y": 03 },
        { "x": 23, "y": 03 },
        { "x": 06, "y": 04 },
        { "x": 14, "y": 04 },
        { "x": 23, "y": 04 },
        { "x": 24, "y": 04 },
        { "x": 25, "y": 04 },
        { "x": 26, "y": 04 },
        { "x": 06, "y": 05 },
        { "x": 14, "y": 05 },
        { "x": 24, "y": 05 },
        { "x": 05, "y": 06 },
        { "x": 06, "y": 06 },
        { "x": 14, "y": 06 },
        { "x": 15, "y": 06 },
        { "x": 16, "y": 06 },
        { "x": 18, "y": 06 },
        { "x": 19, "y": 06 },
        { "x": 20, "y": 06 },
        { "x": 21, "y": 06 },
        { "x": 24, "y": 06 },
        { "x": 05, "y": 07 },
        { "x": 06, "y": 07 },
        { "x": 16, "y": 07 },
        { "x": 17, "y": 07 },
        { "x": 18, "y": 07 },
        { "x": 21, "y": 07 },
        { "x": 22, "y": 07 },
        { "x": 23, "y": 07 },
        { "x": 24, "y": 07 },
        { "x": 21, "y": 08 },
        { "x": 24, "y": 08 },
        { "x": 21, "y": 09 },
        { "x": 24, "y": 09 },
        { "x": 25, "y": 09 },
        { "x": 26, "y": 09 },
        { "x": 27, "y": 09 },
        { "x": 28, "y": 09 },
        { "x": 29, "y": 09 },
        { "x": 21, "y": 10 },
        { "x": 29, "y": 10 },
        { "x": 21, "y": 11 },
        { "x": 29, "y": 11 },
        { "x": 21, "y": 12 },
        { "x": 29, "y": 12 },
        { "x": 21, "y": 13 },
        { "x": 29, "y": 13 },
        { "x": 36, "y": 13 },
        { "x": 40, "y": 13 },
        { "x": 21, "y": 14 },
        { "x": 29, "y": 14 },
        { "x": 36, "y": 14 },
        { "x": 40, "y": 14 },
        { "x": 21, "y": 15 },
        { "x": 23, "y": 15 },
        { "x": 24, "y": 15 },
        { "x": 25, "y": 15 },
        { "x": 26, "y": 15 },
        { "x": 27, "y": 15 },
        { "x": 28, "y": 15 },
        { "x": 29, "y": 15 },
        { "x": 33, "y": 15 },
        { "x": 34, "y": 15 },
        { "x": 35, "y": 15 },
        { "x": 36, "y": 15 },
        { "x": 37, "y": 15 },
        { "x": 38, "y": 15 },
        { "x": 39, "y": 15 },
        { "x": 40, "y": 15 },
        { "x": 21, "y": 16 },
        { "x": 22, "y": 16 },
        { "x": 23, "y": 16 },
        { "x": 29, "y": 16 },
        { "x": 33, "y": 16 },
        { "x": 16, "y": 17 },
        { "x": 17, "y": 17 },
        { "x": 18, "y": 17 },
        { "x": 19, "y": 17 },
        { "x": 20, "y": 17 },
        { "x": 21, "y": 17 },
        { "x": 29, "y": 17 },
        { "x": 30, "y": 17 },
        { "x": 31, "y": 17 },
        { "x": 32, "y": 17 },
        { "x": 33, "y": 17 },
        { "x": 16, "y": 18 },
        { "x": 31, "y": 18 },
        { "x": 16, "y": 19 },
        { "x": 31, "y": 19 },
        { "x": 04, "y": 20 },
        { "x": 05, "y": 20 },
        { "x": 06, "y": 20 },
        { "x": 07, "y": 20 },
        { "x": 08, "y": 20 },
        { "x": 16, "y": 20 },
        { "x": 29, "y": 20 },
        { "x": 30, "y": 20 },
        { "x": 31, "y": 20 },
        { "x": 03, "y": 21 },
        { "x": 04, "y": 21 },
        { "x": 08, "y": 21 },
        { "x": 16, "y": 21 },
        { "x": 29, "y": 21 },
        { "x": 03, "y": 22 },
        { "x": 04, "y": 22 },
        { "x": 08, "y": 22 },
        { "x": 09, "y": 22 },
        { "x": 10, "y": 22 },
        { "x": 11, "y": 22 },
        { "x": 12, "y": 22 },
        { "x": 13, "y": 22 },
        { "x": 14, "y": 22 },
        { "x": 15, "y": 22 },
        { "x": 16, "y": 22 },
        { "x": 29, "y": 22 },
        { "x": 03, "y": 23 },
        { "x": 04, "y": 23 },
        { "x": 29, "y": 23 },
        { "x": 04, "y": 24 },
        { "x": 29, "y": 24 },
        { "x": 04, "y": 25 },
        { "x": 29, "y": 25 },
        { "x": 04, "y": 26 },
        { "x": 05, "y": 26 },
        { "x": 06, "y": 26 },
        { "x": 07, "y": 26 },
        { "x": 08, "y": 26 },
        { "x": 25, "y": 26 },
        { "x": 26, "y": 26 },
        { "x": 27, "y": 26 },
        { "x": 28, "y": 26 },
        { "x": 29, "y": 26 },
        { "x": 08, "y": 27 },
        { "x": 25, "y": 27 },
        { "x": 26, "y": 27 },
        { "x": 08, "y": 28 },
        { "x": 25, "y": 28 },
        { "x": 26, "y": 28 },
        { "x": 25, "y": 29 },
        { "x": 26, "y": 29 },
        { "x": 24, "y": 30 },
        { "x": 25, "y": 30 },
        { "x": 26, "y": 30 },
        { "x": 27, "y": 30 },
        { "x": 24, "y": 31 },
        { "x": 27, "y": 31 },
        { "x": 24, "y": 32 },
        { "x": 27, "y": 32 },
        { "x": 24, "y": 33 },
        { "x": 27, "y": 33 },
        { "x": 24, "y": 34 },
        { "x": 27, "y": 34 },
        { "x": 24, "y": 35 },
        { "x": 27, "y": 35 },
        { "x": 24, "y": 36 },
        { "x": 27, "y": 36 },
        { "x": 24, "y": 37 },
        { "x": 25, "y": 37 },
        { "x": 26, "y": 37 },
        { "x": 27, "y": 37 }
    ]
}

const units = {
    "haven": [
        { "type": "SQUAD", "position": { "x": 25, "y": 20 }, "experience": 1 },
        { "type": "SQUAD", "position": { "x": 22, "y": 27 }, "experience": 1 },
        { "type": "SQUAD", "position": { "x": 18, "y": 19 }, "experience": 1 },
        { "type": "LTTANK", "position": { "x": 26, "y": 32 }, "experience": 1 },
        { "type": "TROOP", "position": { "x": 30, "y": 29 }, "experience": 1 },
        { "type": "TROOP", "position": { "x": 26, "y": 20 }, "experience": 1 },
        { "type": "LTTANK", "position": { "x": 30, "y": 22 }, "experience": 1 },
        { "type": "LTTANK", "position": { "x": 30, "y": 26 }, "experience": 1 }
    ],
    "eagle-nest": [
        { "position": { "x": 23, "y": 25 }, "type": "LONGRANGE", "experience": 1 },
        { "position": { "x": 25, "y": 28 }, "type": "TANK", "experience": 1 },
        { "position": { "x": 03, "y": 23 }, "type": "TANK", "experience": 1 },
        { "position": { "x": 03, "y": 21 }, "type": "TANK", "experience": 1 },
        { "position": { "x": 05, "y": 07 }, "type": "TANK", "experience": 1 },
        { "position": { "x": 21, "y": 27 }, "type": "SQUAD", "experience": 1 },
        { "position": { "x": 31, "y": 17 }, "type": "SQUAD", "experience": 1 },
        { "position": { "x": 27, "y": 24 }, "type": "SQUAD", "experience": 1 },
        { "position": { "x": 26, "y": 28 }, "type": "TANK", "experience": 1 }
    ]
};

const structures = {
    "haven": [
        { "position": { "x": 20, "y": 24 }, "type": "ENERGY" },
        { "position": { "x": 20, "y": 27 }, "type": "ENERGY" },
        { "position": { "x": 18, "y": 24 }, "type": "ENERGY" },
        { "position": { "x": 18, "y": 27 }, "type": "ENERGY" },
        { "position": { "x": 27, "y": 23 }, "type": "MINING" },
        { "position": { "x": 18, "y": 21 }, "type": "MINING" },
        { "position": { "x": 28, "y": 19 }, "type": "TOWER" },
        { "position": { "x": 27, "y": 20 }, "type": "BARRACKS" },
        { "position": { "x": 22, "y": 20 }, "type": "FACTORY" },
        { "position": { "x": 31, "y": 22 }, "type": "AIRPORT" },
        { "position": { "x": 23, "y": 29 }, "type": "LAB" },
        { "position": { "x": 23, "y": 31 }, "type": "LAB" },
        { "position": { "x": 24, "y": 27 }, "type": "SCANNER" },
        {
            "position": { "x": 23, "y": 24 },
            "type": "DROPSHIP",
            "units": [
                { "type": "TROOP", "experience": 1 },
                { "type": "SQUAD", "experience": 1 },
                { "type": "LTTANK", "experience": 1 },
            ]
        },
        { "position": { "x": 27, "y": 27 }, "type": "STARPORT" }
    ],
    "eagle-nest": [
        { "position": { "x": 07, "y": 00 }, "type": "ENERGY" },
        { "position": { "x": 09, "y": 20 }, "type": "ENERGY" },
        { "position": { "x": 11, "y": 00 }, "type": "ENERGY" },
        { "position": { "x": 07, "y": 06 }, "type": "ENERGY" },
        { "position": { "x": 18, "y": 18 }, "type": "ENERGY" },
        { "position": { "x": 03, "y": 03 }, "type": "MINING" },
        { "position": { "x": 04, "y": 17 }, "type": "MINING" },
        { "position": { "x": 33, "y": 21 }, "type": "TOWER" },
        { "position": { "x": 30, "y": 19 }, "type": "TOWER" },
        { "position": { "x": 31, "y": 16 }, "type": "TOWER" },
        { "position": { "x": 23, "y": 36 }, "type": "TOWER" },
        { "position": { "x": 25, "y": 36 }, "type": "TOWER" },
        { "position": { "x": 26, "y": 36 }, "type": "TOWER" },
        { "position": { "x": 28, "y": 36 }, "type": "TOWER" },
        { "position": { "x": 27, "y": 29 }, "type": "TOWER" },
        { "position": { "x": 24, "y": 29 }, "type": "TOWER" },
        { "position": { "x": 28, "y": 16 }, "type": "TOWER" },
        { "position": { "x": 26, "y": 05 }, "type": "TOWER" },
        { "position": { "x": 38, "y": 13 }, "type": "TOWER" },
        { "position": { "x": 26, "y": 33 }, "type": "TOWER" },
        { "position": { "x": 25, "y": 33 }, "type": "TOWER" },
        { "position": { "x": 18, "y": 04 }, "type": "BARRACKS" },
        { "position": { "x": 00, "y": 21 }, "type": "FACTORY" },
        { "position": { "x": 14, "y": 20 }, "type": "LAB" },
        { "position": { "x": 05, "y": 08 }, "type": "ANTIMISSILE" },
        { "position": { "x": 17, "y": 08 }, "type": "SCANNER" }
    ]
};

const createUnitInstance = (side) => {
    const unitLookup = {
        'HUMAN': {
            "SQUAD": "HSQU",
            "TROOP": "HRAN",
            "LTTANK": "HATV",
            "LONGRANGE": "HART",
            "UNIQUE1": "HBUG",
            "TANK": "HTNK",
            "LTGRAV": "HSPE",
            "HEAVYGRAV": "HGRV",
            "LONGRANGEHOVER": "HGUN"
        },
        'ALIEN': {
            "SQUAD": "ASQD",
            "TROOP": "ASNI",
            "LTTANK": "ALTK",
            "LONGRANGE": "APLA",
            "HEAVYGRAV": "AGRV",
            "LTGRAV": "AFLY",
            "TANK": "AMDT",
            "LONGRANGEHOVER": "ASUP",
            "UNIQUE1": "AMEG"
        }
    }[side];
    return (result, object) => {
        const ref = UnitData[unitLookup[object.type]];
        const pos = object.position ? {
            "x": object.position.x,
            "y": object.position.y
        } : null;
        result[uuidv4()] = {
            "kind": ref.kind,
            "position": pos,
            "experience": object.experience,
            "hp": ref.hp,
            "facing": 0
        };
        return result;
    }
}

const createStructureInstance = (side) => {
    const structureLookup = {
        'HUMAN': {
            "AIRPORT": "HAIR",
            "ANTIMISSILE": "HDEF",
            "BARRACKS": "HBAR",
            "DROPSHIP": "HSHP",
            "ENERGY": "HENY",
            "FACTORY": "HFAC",
            "LAB": "HLAB",
            "MINING": "HMIN",
            "MISSILE": "HSIL",
            "SCANNER": "HRAD",
            "STARPORT": "HBAY",
            "TOWER": "HTUR"
        },
        'ALIEN': {
            "AIRPORT": "AAIR",
            "ANTIMISSILE": "ADEF",
            "BARRACKS": "ABAR",
            "DROPSHIP": "ASHP",
            "ENERGY": "AENY",
            "FACTORY": "AFAC",
            "LAB": "ALAB",
            "MINING": "AMIN",
            "MISSILE": "ASIL",
            "SCANNER": "ARAD",
            "STARPORT": "ABAY",
            "TOWER": "ATUR"
        }
    }[side];
    return (result, object) => {
        const ref = StructureData[structureLookup[object.type]];
        const units = (object.units || []).reduce(createUnitInstance(side), {});
        const pos = object.position ? {
            "x": object.position.x,
            "y": object.position.y
        } : null;
        result[uuidv4()] = {
            "hp": ref.hp,
            "kind": ref.kind,
            "units": units,
            "position": pos,
        }
        return result;
    }
}

const addExtendedProvinceInformation = (key, side, province) => {
    province.mission = missions[key];
    province.walls = province.walls || walls[key] || [];
    province.roads = province.roads || roads[key] || [];
    province.units = (province.units || units[key] || []).reduce(createUnitInstance(side), {});
    province.structures = (province.structures || structures[key] || []).reduce(createStructureInstance(side), {});
    // TODO: this should look at the structures and units to decide sensible values
    province.energy = 123;
    province.credits = 123;
    province.research = 123;
    return province;
};

const cash = [4000, 6000, 8000];

module.exports.generateGame = (userId, name, race, difficulty, campaignType) => {
    const side = ['HUMAN', 'ALIEN'][race];
    const sides = {};
    sides[userId] = {
        "globalReserve": cash[difficulty],
        "name": name,
        "type": "PLAYER",
        "owner": side,
        "difficulty": difficulty,
        "technology": {
            "energy-efficiency": 0,
            "armour": 0,
            "speed": 0,
            "weapon-damage": 0,
            "rate-of-fire": 0,
            "rocketry": 0
        }
    };

    // generate AI opponent
    // the id should be generated each time to avoid having lots of 'players' with the same id
    const computerId = uuidv4();
    sides[computerId] = {
        "globalReserve": cash[2 - difficulty],
        "name": "Computer",
        "type": "AI",
        "owner": gameService.opposite(side),
        "difficulty": difficulty,
        "technology": {
            "energy-efficiency": 0,
            "armour": 0,
            "speed": 0,
            "weapon-damage": 0,
            "rate-of-fire": 0,
            "rocketry": 0
        }
    };
    const game = {
        "id": uuidv4(),
        "turn": {
            "seed": Math.floor(Math.random() * Math.floor(2147483647)),
            "number": 1,
            "action": 0,
            "kind": "STRATEGIC", // or TACTICAL
            "owner": side // starts on your turn
        },
        "sides": sides,
        "provinces": {
            "cartasone": { "owner": "NEUTRAL" },
            "eagle-nest": { "owner": "NEUTRAL" },
            "haven": { "owner": side, "capital": side /* always own haven */ },
            "free-city": { "owner": side, "capital": side /* you only own this side */ },
            "lachine": { "owner": gameService.opposite(side) },
            "sutton": { "owner": gameService.opposite(side) },
            "milos": { "owner": "NEUTRAL" },
            "high-point": { "owner": "NEUTRAL" },
            "ayden": { "owner": "NEUTRAL" },
            "snake-river": { "owner": "NEUTRAL" },
            "canuck": { "owner": "NEUTRAL" },
            "point-harbour": { "owner": "NEUTRAL" },
            "rock-castle": { "owner": "NEUTRAL" },
            "sparta": { "owner": "NEUTRAL" },
            "aberdeen": { "owner": "NEUTRAL" },
            "delos": { "owner": "NEUTRAL" },
            "elkin": { "owner": "NEUTRAL" },
            "norwood": { "owner": "NEUTRAL" },
            "kinabal": { "owner": "NEUTRAL" },
            "marshall": { "owner": "NEUTRAL" },
            "roanoke": { "owner": "NEUTRAL" },
            "creedmoor": { "owner": "NEUTRAL" },
            "garland": { "owner": "NEUTRAL" },
            "chaos": { "owner": gameService.opposite(side), "capital": gameService.opposite(side) },
            "rolland": { "owner": gameService.opposite(side) },
            "chertsy": { "owner": gameService.opposite(side) },
            "bromont": { "owner": gameService.opposite(side) },
            "rawdon": { "owner": gameService.opposite(side) },
            "granby": { "owner": gameService.opposite(side) },
            "alma": { "owner": gameService.opposite(side) },
            "brome-lake": { "owner": gameService.opposite(side) },
            "hull": { "owner": gameService.opposite(side) },
            "norenda": { "owner": gameService.opposite(side) },
            "brimstone": { "owner": gameService.opposite(side), "capital": gameService.opposite(side) },
            "thetfordmines": { "owner": gameService.opposite(side) },
            "sherbrooke": { "owner": gameService.opposite(side) },
            "masson-lake": { "owner": gameService.opposite(side) },
            "kamouraska": { "owner": gameService.opposite(side) },
            "esterel": { "owner": gameService.opposite(side) },
            "valleyfield": { "owner": gameService.opposite(side) },
            "orford": { "owner": gameService.opposite(side) },
            "three-rivers": { "owner": gameService.opposite(side) }
        }
    };

    // We generate the starting information for both campaign types
    // then filter the data we save to the backend for simplicity
    const campaign = campaigns.provinces[campaignType];
    game.defaultProvince = campaigns.startingProvinces[campaignType];
    game.provinces = Object.keys(game.provinces)
        .filter(province => campaign.includes(province))
        .reduce((provinces, province) => {
            let data = game.provinces[province];
            provinces[province] = addExtendedProvinceInformation(province, side, data);
            return provinces;
        }, {})
    return game;
};
