FROM node:12-alpine

COPY shared/package*.json /src/shared/

WORKDIR /src/shared

RUN npm ci --only=production

COPY ./shared /src/shared

COPY backend/package*.json /src/backend/

WORKDIR /src/backend

RUN npm ci --only=production

COPY ./backend /src/backend

EXPOSE 4500

CMD npm start
