FROM node:10-alpine as build-stage

COPY shared/package*.json /src/shared/

WORKDIR /src/shared

RUN npm install --silent

COPY ./shared /src/shared

WORKDIR /src/frontend

COPY frontend/package*.json /src/frontend/

RUN npm install --silent

COPY ./frontend /src/frontend

RUN npm run build

FROM nginx:1.17-alpine

COPY --from=build-stage /src/frontend/dist/ /usr/share/nginx/html

COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
