FROM node:12-alpine as build-stage

COPY shared/package*.json /src/shared/

WORKDIR /src/shared

RUN npm ci --only=production

COPY ./shared /src/shared

WORKDIR /src/frontend

COPY ./frontend /src/frontend

RUN npm ci

RUN npm run build

FROM nginx:1.17-alpine

COPY --from=build-stage /src/frontend/dist/ /usr/share/nginx/html

COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000
