name: Build and Deploy to Kubernetes

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: azure/docker-login@v1
      with:
        login-server: fallenhaven.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build frontend
      run: |
        # .env file is copied as part of Dockerfile
        echo "API_ENDPOINT=$API_ENDPOINT" >> frontend/.env

        docker build frontend -t fallenhaven.azurecr.io/frontend:${{ github.run_id }}
        docker push fallenhaven.azurecr.io/frontend:${{ github.run_id }}
      env:
        API_ENDPOINT: https://api.fallenhaven.jasoncabot.me

    - name: Build backend
      run: |
        # .env file is copied as part of Dockerfile
        echo "REDIS_HOST=$REDIS_HOST" >> backend/.env
        echo "REDIS_KEY=$REDIS_KEY" >> backend/.env
        echo "REDIS_PORT=$REDIS_PORT" >> backend/.env
        echo "PORT=$PORT" >> backend/.env

        docker build backend -t fallenhaven.azurecr.io/backend:${{ github.run_id }}
        docker push fallenhaven.azurecr.io/backend:${{ github.run_id }}
      env:
        REDIS_HOST: ${{ secrets.REDIS_HOST }}
        REDIS_KEY: ${{ secrets.REDIS_KEY }}
        REDIS_PORT: ${{ secrets.REDIS_PORT }}
        PORT: 4500

    - uses: azure/setup-kubectl@v1
      with:
        version: 'v1.15.5' # default is latest stable
      id: install

    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: '${{ secrets.CLUSTER_NAME }}'
        resource-group: '${{ secrets.CLUSTER_RESOURCE_GROUP }}'
      id: login
    
    # This is a quick/hacky workaround for a strange bug that prevented a deployment
    - name: Delete old deployment
      id: delete
      run: |
        kubectl delete deployment fallenhaven-backend --ignore-not-found
        kubectl delete deployment fallenhaven-frontend --ignore-not-found
          
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
            manifests/frontend.yaml
        images: 'fallenhaven.azurecr.io/frontend:${{ github.run_id }}'
          
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
            manifests/backend.yaml
        images: 'fallenhaven.azurecr.io/backend:${{ github.run_id }}'
