name: Build and Deploy Frontend

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: azure/docker-login@v1
      with:
        login-server: fallenhaven.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build frontend -t fallenhaven.azurecr.io/frontend:${{ github.sha }}
        docker push fallenhaven.azurecr.io/frontend:${{ github.sha }}

    - uses: azure/setup-kubectl@v1
      with:
        version: 'v1.15.5' # default is latest stable
      id: install

    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: 'prod'
        resource-group: 'diceatthetable'
      id: login
    
    - name: Delete old deployment
      id: delete
      run: kubectl delete deployment fallenhaven-frontend --ignore-not-found
          
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
            manifests/frontend.yaml
        images: 'fallenhaven.azurecr.io/frontend:${{ github.sha }}'
